
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

#main functions
def check_input_valid():
    if (entry_name.get() != "" and entry_day.get() != "" and entry_month.get() != "" and entry_year.get() != ""):
        pass


window = Tk()

window.geometry("1000x800")
window.configure(bg = "#2A0404")


canvas = Canvas(
    window,
    bg = "#2A0404",
    height = 800,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    500.0,
    400.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    584.0,
    245.5,
    image=entry_image_1
)
entry_name = Entry(
    bd=0,
    bg="#678799",
    highlightthickness=0,
    font = ("Arial", 50)
)
entry_name.place(
    x=250.5,
    y=183.0,
    width=667.0,
    height=123.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    85.0,
    247.0,
    image=image_image_2
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    488.5,
    588.0,
    image=entry_image_2
)
entry_month = Entry(
    bd=0,
    bg="#C8D075",
    highlightthickness=0,
    font = ("ink Free", 40)
)
entry_month.place(
    x=451.0,
    y=540.0,
    width=75.0,
    height=94.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=362.0,
    y=672.0,
    width=247.0,
    height=94.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    500.0,
    505.0,
    image=image_image_3
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    138.5,
    587.5,
    image=entry_image_3
)
entry_day = Entry(
    bd=0,
    bg="#4294B7",
    highlightthickness=0,
    font = ("ink Free", 40)
)
entry_day.place(
    x=100.0,
    y=559.0,
    width=120.0,
    height=55.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    843.0,
    587.5,
    image=entry_image_4
)
entry_year = Entry(
    bd=0,
    bg="#A6B8F8",
    highlightthickness=0,
    font = ("ink Free", 40)
)
entry_year.place(
    x=785.0,
    y=559.0,
    width=128.0,
    height=55.0
)
window.resizable(False, False)
window.mainloop()
